services:
  vminsert:
    image: victoriametrics/vminsert:latest
    container_name: vminsert
    command:
      - "-retentionPeriod=31"
      - "-storageNode=vm-vip:8400"
    networks:
      - vm_net
    restart: always

  vmselect:
    image: victoriametrics/vmselect:latest
    container_name: vmselect
    command:
      - "-retentionPeriod=31"
      - "-storageNode=vm-vip:8400"
    networks:
      - vm_net
    restart: always

  vmstorage:
    image: victoriametrics/vmstorage:latest
    container_name: vmstorage
    command:
      - "-retentionPeriod=31"
      - "-storageDataPath=/storage"
    volumes:
      - ./storage:/storage
    ports:
      - "8400:8400"
    networks:
      - vm_net
    restart: always

  nginx:
    image: nginx:stable
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8480:8480"
      - "8481:8481"
    networks:
      - vm_net
    restart: always

  keepalived:
    image: osixia/keepalived:latest
    container_name: keepalived
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./keepalived/keepalived.conf:/container/service/keepalived/assets/keepalived.conf
    environment:
      - KEEPALIVED_INTERFACE=eth0
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules:/etc/prometheus/alert.rules
      - ./prometheus/scrape_configs:/etc/prometheus/scrape_configs
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-lifecycle"
    ports:
      - "9090:9090"
    networks:
      - vm_net
    restart: always

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./prometheus/alertmanager:/etc/alertmanager/
    command: 
      - "--config.file=/etc/alertmanager/config.yaml"
      - "--web.listen-address=0.0.0.0:9093"
      - "--cluster.listen-address=0.0.0.0:9094"
      - "--cluster.advertise-address=192.168.21.13:9094"
      - "--cluster.peer=192.168.21.14:9094"
    ports:
      - 9093:9093
    networks:
      - vm_net
    restart: always

networks:
  vm_net:
    driver: bridge
